### ISSUE TITLE
Code blocks don't render indented (`''`) strings correctly

### ISSUE THREAD

**Issue by henrispriet** [NixOS/nixos-wiki-infra#143]
The single quotes of indented strings aren't rendered in code blocks.
For example on [here](https://wiki.nixos.org/wiki/NixOS_VM_tests#home-manager_example) at the bottom of the code block, near `testScript`. The same problem occurs in other code blocks on the same page.

This makes it annoying to copy and paste and is just plain incorrect.

**Comment by detroyejr** [comment]
[The wiki treats nix's doubled single quotes as syntax for _italics_.](https://www.mediawiki.org/wiki/Help:Formatting#Text_formatting_markup) If you inspect the block, you'll see an `<i></i>` element where the quotes ought to be. 

The fix is probably just to replace these with actual code blocks instead of preformatted text? [See the code block at the bottom of this page](https://wiki.nixos.org/wiki/Plex) where highlighting and text render correctly.

**Comment by Mic92** [comment]
We have a proper extension that render things correctly:

```
<syntaxhighlight lang="nix">
</syntaxhighlight>
```

This should be preferred over mediawiki's version.
